# Site settings

title: UCLU TechSoc
email: contact@uclutech.com
description: UCL Technology Society
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uclutech.com" # the base hostname & protocol for your site
timezone: "Europe/London"

# Social media

twitter_username: uclutech
github_username: techsoc
facebook_username: UCLUTechSoc
linkedin_url: https://www.linkedin.com/company/uclu-techsoc

# Build settings

permalink: /blog/:year/:month/:day/:title/
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
exclude:
  - README.md
  - Gemfile*
  - node_modules
  - package.json
  - bower.json
  - gulpfile.js
  - assets/bower_components
  - facebook-sync

# Collections

collections:
  members:
  sponsors:
  events:
    output: true
    permalink: /events/:path/
  series:
    output: true
    permalink: /series/:path/
  jobs:
    output: true
    permalink: /jobs/:path/
  projects:
    output: true
    permalink: /projects/:path/
  redirects:
    output: true
    permalink: /:path/
  calendars:
    output: true

defaults:
  -
    scope:
      path: ""
      type: events
    values:
      layout: event
  -
    scope:
      path: ""
      type: series
    values:
      layout: series
  -
    scope:
      path: ""
      type: jobs
    values:
      layout: job
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: calendars
    values:
      layout: calendar
      include_label: true

gems:
  - jekyll-feed
  - jekyll-redirect-from
